### ISSUE TITLE
Can this be applied to string resources?

### ISSUE THREAD

**Issue by djzara** [christopherney/Enigma#8]
Amazing plugin!! I absolutely adore it and it's made my life leaps and bounds easier.

Now, is it possible to use this on a string resource file to encrypt the strings at build time like the rest? I'd rather not manage encrypted values in the Java code itself, and instead in xml. However, if that's just not doable no worries, I figured I'd check.

Thanks!

**Comment by christopherney** [comment]
Hi @djzara,

Thanks for your feedback. Enigma doesn't encrypt resource files because there is plenty of other good solutions for that on GitHub.

However, from my point of view, I doesn't embed sensitive data in resource file which are to easy to reverse engineer, that why I focused on JAVA source code. At the same time Enigma inject fake data into the code to make harder the hacker job.

BR

**Comment by djzara** [comment]
Believe you me I wouldn't be storing this stuff like I need to if I had a choice lol

Figured I'd ask, much appreciated!!
